apiVersion: k8s.rancher2.m.contrib.crossplane.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    certs: ${base64encode(<PUBLIC_CERTS>)}
    description: Terraform certificate foo
    keySecretRef:
      key: example-key
      name: example-secret
    name: foo
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
