apiVersion: auth.rancher2.m.contrib.crossplane.io/v1alpha1
kind: AuthConfigGithub
metadata:
  annotations:
    meta.upbound.io/example-id: auth/v1alpha1/authconfiggithub
  labels:
    testing.upbound.io/example-name: github
  name: github
  namespace: crossplane-system
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
    clientSecretSecretRef:
      key: example-key
      name: example-secret
