apiVersion: auth.rancher2.m.contrib.crossplane.io/v1alpha1
kind: AuthConfigFreeipa
metadata:
  annotations:
    meta.upbound.io/example-id: auth/v1alpha1/authconfigfreeipa
  labels:
    testing.upbound.io/example-name: freeipa
  name: freeipa
  namespace: crossplane-system
spec:
  forProvider:
    port: 389
    servers:
    - <FREEIPA_SERVER>
    serviceAccountDistinguishedNameSecretRef:
      key: example-key
      name: example-secret
    serviceAccountPasswordSecretRef:
      key: example-key
      name: example-secret
    testPasswordSecretRef:
      key: example-key
      name: example-secret
    testUsername: <USER_NAME>
    userSearchBase: <SEARCH_BASE>
