apiVersion: auth.rancher2.m.contrib.crossplane.io/v1alpha1
kind: AuthConfigActivedirectory
metadata:
  annotations:
    meta.upbound.io/example-id: auth/v1alpha1/authconfigactivedirectory
  labels:
    testing.upbound.io/example-name: activedirectory
  name: activedirectory
  namespace: crossplane-system
spec:
  forProvider:
    port: 389
    servers:
    - <ACTIVEDIRECTORY_SERVER>
    serviceAccountPasswordSecretRef:
      key: example-key
      name: example-secret
    serviceAccountUsernameSecretRef:
      key: example-key
      name: example-secret
    testPasswordSecretRef:
      key: example-key
      name: example-secret
    testUsername: <USER_NAME>
    userSearchBase: <SEARCH_BASE>
