apiVersion: k8s.rancher2.contrib.crossplane.io/v1alpha1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/registry
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: Terraform registry foo
    name: foo
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    registries:
    - address: test.io
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      username: user
