apiVersion: k8s.rancher2.contrib.crossplane.io/v1alpha1
kind: SecretV2
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/secretv2
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dataSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: foo
