apiVersion: k8s.rancher2.contrib.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: k8s/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    dataSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    description: Terraform secret foo
    name: foo
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
