apiVersion: auth.rancher2.contrib.crossplane.io/v1alpha1
kind: AuthConfigPing
metadata:
  annotations:
    meta.upbound.io/example-id: auth/v1alpha1/authconfigping
  labels:
    testing.upbound.io/example-name: ping
  name: ping
spec:
  forProvider:
    displayNameField: <DISPLAY_NAME_FIELD>
    groupsField: <GROUPS_FIELD>
    idpMetadataContentSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    rancherApiHost: https://<RANCHER_API_HOST>
    spCertSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    spKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    uidField: <UID_FIELD>
    userNameField: <USER_NAME_FIELD>
